#define BITRUNNER_COST_NONE 0
#define BITRUNNER_COST_LOW 1
#define BITRUNNER_COST_MEDIUM 2
#define BITRUNNER_COST_HIGH 3

#define BITRUNNER_REWARD_MIN 1
#define BITRUNNER_REWARD_LOW 3
#define BITRUNNER_REWARD_MEDIUM 4
#define BITRUNNER_REWARD_HIGH 5

#define BITRUNNER_DIFFICULTY_NONE 0
#define BITRUNNER_DIFFICULTY_LOW 1
#define BITRUNNER_DIFFICULTY_MEDIUM 2
#define BITRUNNER_DIFFICULTY_HIGH 3

#define DOMAIN_NO_NOHIT_BONUS (1<<0)
#define DOMAIN_TEST_ONLY (1<<1)
#define DOMAIN_FORBIDS_ITEMS (1<<2)
#define DOMAIN_FORBIDS_ABILITIES (1<<3)

#define BITRUNNER_GEAR_LOAD_FAILED (1<<0)
#define BITRUNNER_GEAR_LOAD_BLOCKED (1<<1)

#define BITRUNNER_POINTS_PER_REWARD 100

#define ALERT_BITRUNNER_COMPLETED "bitrunner_completed"
#define ALERT_BITRUNNER_CROWBAR "bitrunner_crowbar"
#define ALERT_BITRUNNER_INTEGRITY "bitrunner_integrity"
#define ALERT_BITRUNNER_SHUTDOWN "bitrunner_shutdown"
