#define VOICE_CHAT_PROTOCOL_VERSION 1

#define VOICE_CHAT_STATUS_DISABLED "disabled"
#define VOICE_CHAT_STATUS_DISCONNECTED "disconnected"
#define VOICE_CHAT_STATUS_CONNECTING "connecting"
#define VOICE_CHAT_STATUS_CONNECTED "connected"
#define VOICE_CHAT_STATUS_RELAY_UNAVAILABLE "relay_unavailable"
#define VOICE_CHAT_STATUS_ERROR "error"

#define VOICE_CHAT_DEFAULT_INPUT_GAIN 100
#define VOICE_CHAT_DEFAULT_OUTPUT_VOLUME 100
#define VOICE_CHAT_MAX_DEVICES 32
#define VOICE_CHAT_MAX_DEVICE_NAME_LENGTH 128
#define VOICE_CHAT_MAX_ERROR_LENGTH 256
#define VOICE_CHAT_MAX_TOKEN_LENGTH 512

