#define VOICE_CHAT_PROTOCOL_VERSION 1
#define VOICE_CHAT_HELPER_FEATURE_VERSION 2

#define VOICE_CHAT_TRANSMISSION_PUSH_TO_TALK "push_to_talk"
#define VOICE_CHAT_TRANSMISSION_VOICE_ACTIVATION "voice_activation"

#define VOICE_CHAT_STATUS_DISABLED "disabled"
#define VOICE_CHAT_STATUS_DISCONNECTED "disconnected"
#define VOICE_CHAT_STATUS_CONNECTING "connecting"
#define VOICE_CHAT_STATUS_CONNECTED "connected"
#define VOICE_CHAT_STATUS_RELAY_UNAVAILABLE "relay_unavailable"
#define VOICE_CHAT_STATUS_ERROR "error"

#define VOICE_CHAT_DEFAULT_INPUT_GAIN 100
#define VOICE_CHAT_DEFAULT_OUTPUT_VOLUME 100
#define VOICE_CHAT_DEFAULT_ACTIVATION_THRESHOLD 15
#define VOICE_CHAT_MIN_ACTIVATION_THRESHOLD 1
#define VOICE_CHAT_MAX_ACTIVATION_THRESHOLD 100
#define VOICE_CHAT_MAX_DEVICES 32
#define VOICE_CHAT_MAX_DEVICE_NAME_LENGTH 128
#define VOICE_CHAT_MAX_ERROR_LENGTH 256
#define VOICE_CHAT_MAX_TOKEN_LENGTH 512

#define VOICE_CHAT_LOOPBACK_IPV4 "127.0.0.1"
#define VOICE_CHAT_LOOPBACK_IPV6 "::1"
#define VOICE_CHAT_HTTP_PREFIX "http://"
#define VOICE_CHAT_HTTPS_PREFIX "https://"
#define VOICE_CHAT_WS_PREFIX "ws://"
#define VOICE_CHAT_WSS_PREFIX "wss://"
#define VOICE_CHAT_CONNECT_PATH "/v1/connect"
#define VOICE_CHAT_DOWNLOAD_PATH "/download/windows"
#define VOICE_CHAT_HELPER_BROKER_URL "http://127.0.0.1:6191/launch"
