/datum/unit_test/room_test/resomi_mechanics

/datum/unit_test/room_test/resomi_mechanics/Run()
	var/mob/living/carbon/human/resomi = allocate(/mob/living/carbon/human)
	resomi.set_species(/datum/species/resomi)
	TEST_ASSERT(resomi.pass_flags & PASSTABLE, "resomi cannot run over tables")
	TEST_ASSERT(HAS_TRAIT(resomi, TRAIT_SMALL_MOB), "resomi is not a small mob")
	TEST_ASSERT_EQUAL(resomi.mob_size, MOB_SIZE_SMALL, "resomi has a human-sized body")
	passtable_on(resomi, DNA_TRAIT)
	passtable_off(resomi, DNA_TRAIT)
	TEST_ASSERT(resomi.pass_flags & PASSTABLE, "curing dwarfism stops resomi from running over tables")
	TEST_ASSERT(istype(resomi.get_organ(BODY_ZONE_TAIL), /obj/item/organ/external/tail/resomi), "resomi grows a generic tail with no sprite")
	TEST_ASSERT(HAS_TRAIT(resomi, TRAIT_GOOD_HEARING), "resomi ears do not give good hearing")
	var/obj/item/organ/internal/eyes/eyes = resomi.get_int_organ(/obj/item/organ/internal/eyes)
	TEST_ASSERT_EQUAL(eyes.see_in_dark, 5, "resomi night vision is not five tiles")
	TEST_ASSERT_EQUAL(resomi.blood_volume, BLOOD_VOLUME_NORMAL * 0.6, "resomi blood volume is not 40% lower")
	for(var/damage_type in list(BRUTE, BURN, TOX, OXY, CLONE, STAMINA, BRAIN))
		TEST_ASSERT_EQUAL(resomi.get_incoming_damage_modifier(10, damage_type), 1.3, "resomi takes the wrong amount of [damage_type] damage")
	var/obj/item/gun/heavy = allocate(/obj/item/gun/projectile/automatic/l6_saw)
	TEST_ASSERT_NOT(resomi.can_use_guns(heavy), "resomi fired a heavy machine gun")
	var/obj/item/gun/light = allocate(/obj/item/gun/energy/laser)
	TEST_ASSERT(resomi.can_use_guns(light), "resomi cannot fire a laser rifle")

	var/mob/living/carbon/human/carrier = allocate(/mob/living/carbon/human)
	var/obj/item/holder/held = resomi.get_scooped(carrier)
	TEST_ASSERT(istype(held, /obj/item/holder/humanoid), "resomi was not picked up")
	TEST_ASSERT_EQUAL(held.w_class, WEIGHT_CLASS_SMALL, "a held resomi does not weigh as a small item")
	TEST_ASSERT(resomi.loc == held && held.loc == carrier, "the picked up resomi is not in the carrier's hands")
	carrier.equip_to_slot_or_del(new /obj/item/clothing/under/color/grey(carrier), ITEM_SLOT_CLOTH_INNER)
	TEST_ASSERT_NOT(carrier.can_equip(held, ITEM_SLOT_POCKET_LEFT, disable_warning = TRUE), "a held resomi fits into a jumpsuit pocket")
	var/obj/item/storage/backpack/bag = allocate(/obj/item/storage/backpack)
	TEST_ASSERT(bag.can_be_inserted(held, stop_messages = TRUE), "a held resomi does not fit into a backpack")
	carrier.drop_item_ground(held)
	bag.handle_item_insertion(held, prevent_warning = TRUE)
	TEST_ASSERT(resomi.is_hiding_in_storage(), "resomi in a backpack does not count as hiding in it")
	TEST_ASSERT_NOT(resomi.can_use_guns(light), "resomi fired a gun from inside a backpack")
	TEST_ASSERT_NOTNULL(resomi.alerts?[ALERT_PICKUPABLE_CONTAINER], "resomi got no alert to open the backpack it sits in")
	qdel(bag)
	TEST_ASSERT(!QDELETED(resomi) && isturf(resomi.loc), "deleting the backpack deleted the resomi sitting in it")

	resomi.change_body_accessory("Spiky tail")
	resomi.regenerate_icons()
	TEST_ASSERT_NOTNULL(resomi.overlays_standing[TAIL_LAYER], "the resomi tail is drawn under the body when seen from behind")
