DEFINE_BITFIELD(department_flag, list(
	"JOBCAT_ENGSEC" = JOBCAT_ENGSEC,
	"JOBCAT_MEDSCI" = JOBCAT_MEDSCI,
	"JOBCAT_SUPPORT" = JOBCAT_SUPPORT,
	"JOBCAT_KARMA" = JOBCAT_KARMA,
))

DEFINE_BITFIELD(job_flags, list(
	"JOB_ANTAG_BLACKLISTED" = JOB_ANTAG_BLACKLISTED,
	"JOB_ANTAG_PROTECTED" = JOB_ANTAG_PROTECTED,
))
