<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VoiceChat.Protocol\VoiceChat.Protocol.csproj" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="SoundFlow.Extensions.WebRtc.Apm" Version="1.4.0" />
  </ItemGroup>
</Project>
